/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package l_m;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
/**
 *
 * @author Pedro53722376
 */
public class Home extends javax.swing.JFrame {

        String idPessoa = "";
    
    public String getIdPessoa() {
        return idPessoa;
    }

    public void setIdPessoa(String idPessoa) {
        this.idPessoa = idPessoa;
    }

    /**
     * Creates new form Tela_inicial
     */
    public Home() {
        initComponents();
        imagemFundo1.setImg(new ImageIcon(getClass().getResource("/imgs/background.png")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painel = new javax.swing.JDesktopPane();
        imagemFundo1 = new imagemfundo.ImagemFundo();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        telaAssinantesBt = new javax.swing.JLabel();
        telaProdutosBt = new javax.swing.JLabel();
        telaFuncionarioBt = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        painel.setBackground(new java.awt.Color(255, 255, 255));

        imagemFundo1.setPreferredSize(new java.awt.Dimension(1220, 800));

        jPanel1.setBackground(new java.awt.Color(217, 217, 217));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/Logo.png"))); // NOI18N

        telaAssinantesBt.setFont(new java.awt.Font("Malgun Gothic", 0, 14)); // NOI18N
        telaAssinantesBt.setText("Assinantes");
        telaAssinantesBt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        telaAssinantesBt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                telaAssinantesBtMouseClicked(evt);
            }
        });

        telaProdutosBt.setFont(new java.awt.Font("Malgun Gothic", 0, 14)); // NOI18N
        telaProdutosBt.setText("Produtos");
        telaProdutosBt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        telaProdutosBt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                telaProdutosBtMouseClicked(evt);
            }
        });

        telaFuncionarioBt.setFont(new java.awt.Font("Malgun Gothic", 0, 14)); // NOI18N
        telaFuncionarioBt.setText("Funcionários");
        telaFuncionarioBt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        telaFuncionarioBt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                telaFuncionarioBtMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addGap(233, 233, 233)
                .addComponent(telaAssinantesBt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 239, Short.MAX_VALUE)
                .addComponent(telaProdutosBt)
                .addGap(265, 265, 265)
                .addComponent(telaFuncionarioBt)
                .addGap(187, 187, 187))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(telaAssinantesBt)
                        .addComponent(telaProdutosBt)
                        .addComponent(telaFuncionarioBt))
                    .addComponent(jLabel1))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout imagemFundo1Layout = new javax.swing.GroupLayout(imagemFundo1);
        imagemFundo1.setLayout(imagemFundo1Layout);
        imagemFundo1Layout.setHorizontalGroup(
            imagemFundo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        imagemFundo1Layout.setVerticalGroup(
            imagemFundo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(imagemFundo1Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 680, Short.MAX_VALUE))
        );

        painel.setLayer(imagemFundo1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout painelLayout = new javax.swing.GroupLayout(painel);
        painel.setLayout(painelLayout);
        painelLayout.setHorizontalGroup(
            painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(imagemFundo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        painelLayout.setVerticalGroup(
            painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelLayout.createSequentialGroup()
                .addComponent(imagemFundo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painel)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painel)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void telaAssinantesBtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_telaAssinantesBtMouseClicked
        Tela_lista_assinantes TLA = new Tela_lista_assinantes();
        painel.add(TLA);
        TLA.setVisible(true);
    }//GEN-LAST:event_telaAssinantesBtMouseClicked

    private void telaProdutosBtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_telaProdutosBtMouseClicked
        Tela_produtos TP = new Tela_produtos();
        painel.add(TP);
        TP.setVisible(true);
    }//GEN-LAST:event_telaProdutosBtMouseClicked

    private void telaFuncionarioBtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_telaFuncionarioBtMouseClicked
        if(getIdPessoa().isBlank()){
            JOptionPane.showMessageDialog(null, "Só administradores tem acesso a essa pagina!");
            return;
        }
        Tela_gerenciar_funcionarios TGF = new Tela_gerenciar_funcionarios();
        painel.add(TGF);
        TGF.setVisible(true);
    }//GEN-LAST:event_telaFuncionarioBtMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private imagemfundo.ImagemFundo imagemFundo1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JDesktopPane painel;
    private javax.swing.JLabel telaAssinantesBt;
    private javax.swing.JLabel telaFuncionarioBt;
    private javax.swing.JLabel telaProdutosBt;
    // End of variables declaration//GEN-END:variables
}
