/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package l_m;
import java.sql.ResultSet;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Pedro53722376
 */
public class Recuperar_senha extends javax.swing.JInternalFrame {

    /**
     * Creates new form Recuparar_senha
     */
    public Recuperar_senha() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imagemFundo5 = new imagemfundo.ImagemFundo();
        jLabel21 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        matriculaTxt4 = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        senhaTxt4 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        emailTxt4 = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        btRecuperaSenha4 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/Logo.png"))); // NOI18N

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 10, true));

        matriculaTxt4.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        matriculaTxt4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        matriculaTxt4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                matriculaTxtActionPerformed(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Malgun Gothic", 0, 24)); // NOI18N
        jLabel22.setText("Matrícula:");

        jLabel23.setFont(new java.awt.Font("Malgun Gothic", 0, 24)); // NOI18N
        jLabel23.setText("Senha:");

        senhaTxt4.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        senhaTxt4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        senhaTxt4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                senhaTxtActionPerformed(evt);
            }
        });

        jLabel24.setFont(new java.awt.Font("Malgun Gothic", 1, 36)); // NOI18N
        jLabel24.setText("Recupere sua senha");

        emailTxt4.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        emailTxt4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        emailTxt4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailTxtActionPerformed(evt);
            }
        });

        jLabel25.setFont(new java.awt.Font("Malgun Gothic", 0, 24)); // NOI18N
        jLabel25.setText("Email:");

        btRecuperaSenha4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/btnRecuperaSenha.png"))); // NOI18N
        btRecuperaSenha4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btRecuperaSenha4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btRecuperaSenhaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(matriculaTxt4)
                    .addComponent(senhaTxt4)
                    .addComponent(emailTxt4)))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(193, 193, 193)
                        .addComponent(jLabel22))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(217, 217, 217)
                        .addComponent(jLabel23))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(227, 227, 227)
                        .addComponent(jLabel25)))
                .addGap(0, 73, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btRecuperaSenha4)
                .addGap(153, 153, 153))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(matriculaTxt4, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel25)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(emailTxt4, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(senhaTxt4, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71)
                .addComponent(btRecuperaSenha4)
                .addGap(235, 235, 235))
        );

        javax.swing.GroupLayout imagemFundo5Layout = new javax.swing.GroupLayout(imagemFundo5);
        imagemFundo5.setLayout(imagemFundo5Layout);
        imagemFundo5Layout.setHorizontalGroup(
            imagemFundo5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(imagemFundo5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 347, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        imagemFundo5Layout.setVerticalGroup(
            imagemFundo5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(imagemFundo5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(imagemFundo5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 653, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(imagemFundo5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(imagemFundo5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btRecuperaSenhaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btRecuperaSenhaMouseClicked

        try{
            Connection con = DataBaseConnection.conexaoBanco();
            String sql = "SELECT p.email, p.senha, f.matricula FROM pessoa p INNER JOIN funcionario f ON p.id_pessoa = f.id_pessoa WHERE matricula = ? AND email = ?;";
            PreparedStatement stmt = con.prepareStatement(sql);
            ResultSet rs = stmt.executeQuery();

            stmt.setString(1, matriculaTxt.getText());
            stmt.setString(2, emailTxt.getText());
            stmt.execute();

            while(rs.next()){
                sql = "UPDATE pessoa SET senha = ? WHERE matricula = ?";
                stmt = con.prepareStatement(sql);
                stmt.setString(1, matriculaTxt.getText());
                stmt.execute();
                JOptionPane.showMessageDialog(null, "Senha atualizada com sucesso!");
            }

            rs.close();
            con.close();
            stmt.close();
        }catch(SQLException ex){
            Logger.getLogger(Recuperar_senha.class.getName()).log(Level.SEVERE, null, ex);
        }

        try{
            Connection con = DataBaseConnection.conexaoBanco();
            String sql = "SELECT p.email, p.senha, a.matricula FROM pessoa p INNER JOIN administrador a ON p.id_pessoa = a.id_pessoa WHERE matricula = ? AND email = ?;";
            PreparedStatement stmt = con.prepareStatement(sql);
            ResultSet rs = stmt.executeQuery();

            stmt.setString(1, matriculaTxt.getText());
            stmt.setString(2, emailTxt.getText());
            stmt.execute();

            while(rs.next()){
                sql = "UPDATE pessoa SET senha = ? WHERE matricula = ?";
                stmt = con.prepareStatement(sql);
                stmt.setString(1, matriculaTxt.getText());
                stmt.execute();
                JOptionPane.showMessageDialog(null, "Senha atualizada com sucesso!");
            }

            rs.close();
            con.close();
            stmt.close();
        }catch(SQLException ex){
            Logger.getLogger(Recuperar_senha.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btRecuperaSenhaMouseClicked

    private void emailTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailTxtActionPerformed

    private void senhaTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_senhaTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_senhaTxtActionPerformed

    private void matriculaTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_matriculaTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_matriculaTxtActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btRecuperaSenha;
    private javax.swing.JLabel btRecuperaSenha1;
    private javax.swing.JLabel btRecuperaSenha2;
    private javax.swing.JLabel btRecuperaSenha3;
    private javax.swing.JLabel btRecuperaSenha4;
    private javax.swing.JTextField emailTxt;
    private javax.swing.JTextField emailTxt1;
    private javax.swing.JTextField emailTxt2;
    private javax.swing.JTextField emailTxt3;
    private javax.swing.JTextField emailTxt4;
    private imagemfundo.ImagemFundo imagemFundo1;
    private imagemfundo.ImagemFundo imagemFundo2;
    private imagemfundo.ImagemFundo imagemFundo3;
    private imagemfundo.ImagemFundo imagemFundo4;
    private imagemfundo.ImagemFundo imagemFundo5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTextField matriculaTxt;
    private javax.swing.JTextField matriculaTxt1;
    private javax.swing.JTextField matriculaTxt2;
    private javax.swing.JTextField matriculaTxt3;
    private javax.swing.JTextField matriculaTxt4;
    private javax.swing.JTextField senhaTxt;
    private javax.swing.JTextField senhaTxt1;
    private javax.swing.JTextField senhaTxt2;
    private javax.swing.JTextField senhaTxt3;
    private javax.swing.JTextField senhaTxt4;
    // End of variables declaration//GEN-END:variables
}
